install package providing missing file
Should fix the following travis-ci error, which appeared as we moved
away from the container-based environment:
ERROR:  could not open extension control file /usr/share/postgresql/9.4/extension/postgis.control: No such file or directory